name: GitHub Actions Demo
on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "Hello world"
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 #install the python needed
                            - name: Install dependencies
          run: |
            pip install requirements.txt
      - name: execute py script # run file
        run: |
          python ci.py
